### ISSUE TITLE
Cannot move window

### ISSUE THREAD

**Issue by wagwan-piffting-blud** [VisualFileSorter/VisualFileSorter#12]
Is the option to relocate/move the primary window currently unsupported? I attempted to drag the title bar of the window but nothing happened.

Thanks!

**Comment by VisualFileSorter** [comment]
Thank you for the report.

I have fixed this in 1.12 with code from here:
https://github.com/FrankenApps/Avalonia-CustomTitleBarTemplate/blob/521366625bddf8c295ca9ee1c457201affc4d107/Views/CustomTitleBars/WindowsTitleBar.axaml.cs#L118

https://github.com/VisualFileSorter/VisualFileSorter/releases/tag/1.12
